name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    - name: install JUnit
      run: sudo apt install junit4

    - name: build files
      run: javac -cp .:/usr/share/java/junit4.jar PrimeCheck.java PrimeCheckTest.java

    - name: run tests
      run: java -cp .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore PrimeCheckTest

  test-on-windows:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download JUnit JAR
      run: Invoke-WebRequest -Uri 'https://search.maven.org/remotecontent?filepath=junit/junit/4.13.2/junit-4.13.2.jar' -OutFile 'junit-4.13.2.jar'

    - name: Build files
      run: javac -cp .:/junit-4.13.2.jar PrimeCheck.java PrimeCheckTest.java

    - name: Run tests
      run: java -cp .:/junit-4.13.2.jar org.junit.runner.JUnitCore PrimeCheckTest